"""new_db

Revision ID: 001c47b1f489
Revises: 9bcf92051791
Create Date: 2026-01-06 02:23:20.207709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001c47b1f489'
down_revision = '9bcf92051791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rank', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_data')
    op.drop_table('award_db')
    # ### end Alembic commands ###
