"""Add age column to user table

Revision ID: 155ad51491f0
Revises: 001c47b1f489
Create Date: 2026-01-08 15:53:27.260498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155ad51491f0'
down_revision = '001c47b1f489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_data', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
