"""new migrate

Revision ID: 6ab2f883c395
Revises: a4445d25ebca
Create Date: 2025-09-05 14:46:22.982253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab2f883c395'
down_revision = 'a4445d25ebca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_photo', schema=None) as batch_op:
        batch_op.alter_column('activity_image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('past_member', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('present_member', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('present_member', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('past_member', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('activity_photo', schema=None) as batch_op:
        batch_op.alter_column('activity_image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
