"""Initial migration with all models

Revision ID: a4445d25ebca
Revises: 
Create Date: 2025-09-02 12:26:28.900496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4445d25ebca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aboard_conference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('conference_name', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aboard_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=500), nullable=False),
    sa.Column('activity_image', sa.String(length=100), nullable=False),
    sa.Column('people', sa.String(length=500), nullable=False),
    sa.Column('venue', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domestic_conference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('conference_name', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domestic_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberspec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=500), nullable=False),
    sa.Column('people', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('organi', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=500), nullable=False),
    sa.Column('price', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=500), nullable=False),
    sa.Column('profile_image', sa.String(length=100), nullable=False),
    sa.Column('degree', sa.String(length=500), nullable=False),
    sa.Column('department', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('affiliation', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('present_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=500), nullable=False),
    sa.Column('profile_image', sa.String(length=100), nullable=False),
    sa.Column('degree', sa.String(length=500), nullable=False),
    sa.Column('department', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('interest_part', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('present_member')
    op.drop_table('past_member')
    op.drop_table('memberspec')
    op.drop_table('home_content')
    op.drop_table('domestic_publications')
    op.drop_table('domestic_conference')
    op.drop_table('activity_photo')
    op.drop_table('aboard_publications')
    op.drop_table('aboard_conference')
    # ### end Alembic commands ###
