"""message

Revision ID: ca3b99b47210
Revises: 6ab2f883c395
Create Date: 2025-12-15 22:35:21.007425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3b99b47210'
down_revision = '6ab2f883c395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_photo', schema=None) as batch_op:
        batch_op.drop_column('people')

    # ### end Alembic commands ###
