"""new migrate

Revision ID: e979e4ce7a86
Revises: 155ad51491f0
Create Date: 2026-05-31 16:46:44.158821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e979e4ce7a86'
down_revision = '155ad51491f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award_db', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
