"""Add profile_image to past_member

Revision ID: f8962a0f2495
Revises: 6ab2f883c395
Create Date: 2025-12-24 00:52:54.017208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8962a0f2495'
down_revision = '6ab2f883c395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_photo', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('activity_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('past_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_member', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('activity_photo', schema=None) as batch_op:
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('activity_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
